/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.adminPanel;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Heni Edrianti
 */
public class TablePanel extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    /**
     * Creates new form TablePanel
     */
    public TablePanel() {
        initComponents();
        tableModel = (DefaultTableModel) table.getModel();
        tableModel.addColumn("nama");
        tableModel.addColumn("nama2");
        tableModel.addColumn("nama3");
        tableModel.addColumn("nama4");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setColumnName(String []data){
        System.out.println("column = "+table.getColumnCount());
        if(table == null || table.getColumnCount() != data.length){
            javax.swing.JOptionPane.showMessageDialog(null,"number of column doesn't match number of data","ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        javax.swing.table.JTableHeader header= table.getTableHeader();
        int i=0;
        for(String columnName:data){
            header.getColumnModel().getColumn(i).setHeaderValue(columnName);
            i++;
        }
        header.repaint();
    }
    public int getSelectedRow(){
        return table.getSelectedRow();
    }
    public void addRow(String[]data){
        if(tableModel!=null)
            tableModel.addRow(data);
    }
    public void removeSelectedRow(){
        while(getSelectedRow()>=0){
            tableModel.removeRow(getSelectedRow());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
