/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.adminPanel;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Heni Edrianti
 */
public class TablePanel extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private String[]tableHeader = {"ID","NPSN","Nama","Jam","Status","Keterangan"};
    /**
     * Creates new form TablePanel
     */

    public TablePanel() {
        initComponents();
        tableModel = (DefaultTableModel) table.getModel();
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        for (String val : tableHeader) {
            tableModel.addColumn(val);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(654, 397));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(654, 397));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setPreferredSize(new java.awt.Dimension(654, 397));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setColumnName(String []data){
        System.out.println("column = "+table.getColumnCount());
        if(table == null || table.getColumnCount() != data.length){
            javax.swing.JOptionPane.showMessageDialog(null,"number of column doesn't match number of data","ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        javax.swing.table.JTableHeader header= table.getTableHeader();
        int i=0;
        for(String columnName:data){
            header.getColumnModel().getColumn(i).setHeaderValue(columnName);
            i++;
        }
        header.repaint();
    }
    public void addColumn(String col){
        tableModel.addColumn(col);
    }
    public int getSelectedRow(){
        return table.getSelectedRow();
    }
    public void addRow(String[]data){
        if(tableModel!=null)
            tableModel.addRow(data);
    }
    public void removeSelectedRow(){
        while(getSelectedRow()>=0){
            tableModel.removeRow(getSelectedRow());
        }
    }
    public void clearRows(){
        int numRows = tableModel.getRowCount();
        for(int i=numRows-1;i>=0;i--){
            tableModel.removeRow(i);
        }
    }
    public String[]getRowValue(){
        String []val = new String[tableModel.getColumnCount()];
        
        int row = getSelectedRow();
        for(int i=0;i<val.length;i++){
            val[i] = tableModel.getValueAt(row, i).toString();
        }
        return val;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
